DROP TABLE foodtruck.review;

CREATE TABLE `user` (
   `id` VARCHAR(128) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
   `per` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
   `password` VARCHAR(32) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
   `mail` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
   `name` VARCHAR(32) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
   PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;


CREATE TABLE `food` (
   `fno` INT NOT NULL AUTO_INCREMENT,
   `id` VARCHAR(128) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
   `fname` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
   `fphoto` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
   `flocation` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
   `ftime` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
   `fmenu` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
   `fprice` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
   `fpro` INT NULL DEFAULT NULL,
   `flat` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
   `flon` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
   PRIMARY KEY (`fno`) USING BTREE,
   INDEX `FK_id_food` (`id`) USING BTREE,
   CONSTRAINT `FK_id_food` FOREIGN KEY (`id`) REFERENCES `user` (`id`) ON UPDATE CASCADE ON DELETE CASCADE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;

CREATE TABLE `noti` (
   `nno` INT NOT NULL AUTO_INCREMENT,
   `ntitle` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
   `ncontent` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
   `nregtime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
   `nupdatetime` TIMESTAMP NULL DEFAULT NULL,
   PRIMARY KEY (`nno`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;

CREATE TABLE `info` (
   `ino` INT NOT NULL AUTO_INCREMENT,
   `id` VARCHAR(128) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
   `ilocation` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
   `icontent` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
   `iregtime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (`ino`) USING BTREE,
   INDEX `FK_id_info` (`id`) USING BTREE,
   CONSTRAINT `FK_id_info` FOREIGN KEY (`id`) REFERENCES `user` (`id`) ON UPDATE CASCADE ON DELETE CASCADE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;

CREATE TABLE `review` (
   `fno` INT NULL DEFAULT NULL,
   `id` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
   `point` INT NULL DEFAULT NULL,
   `rcontent` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
   `rregtime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
   `rupdatetime` TIMESTAMP NULL DEFAULT NULL,
   INDEX `fno` (`fno`) USING BTREE,
   INDEX `id` (`id`) USING BTREE,
   CONSTRAINT `FK_fno_review` FOREIGN KEY (`fno`) REFERENCES `food` (`fno`) ON UPDATE CASCADE ON DELETE CASCADE,
   CONSTRAINT `FK_id_review` FOREIGN KEY (`id`) REFERENCES `user` (`id`) ON UPDATE CASCADE ON DELETE CASCADE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;

CREATE TABLE `question` (
   `qno` INT NOT NULL AUTO_INCREMENT,
   `id` VARCHAR(128) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
   `qtitle` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
   `mail` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
   `qcon` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
   `qpro` INT NULL DEFAULT NULL,
   PRIMARY KEY (`qno`) USING BTREE,
   INDEX `FK_id_question` (`id`) USING BTREE,
   CONSTRAINT `FK_id_question` FOREIGN KEY (`id`) REFERENCES `user` (`id`) ON UPDATE CASCADE ON DELETE CASCADE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;


CREATE TABLE `order` (
	`ono` INT NOT NULL AUTO_INCREMENT,
   `fno` INT NULL DEFAULT NULL,
   `id` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
   `menu` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
   `total` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
   `opro` INT NULL DEFAULT NULL,
   PRIMARY KEY (`ono`) USING BTREE,
   INDEX `FK_id_order` (`id`) USING BTREE,
   INDEX `FK_fno_order` (`fno`) USING BTREE,
   CONSTRAINT `FK_id_order` FOREIGN KEY (`id`) REFERENCES `user` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
   CONSTRAINT `FK_fno_order` FOREIGN KEY (`fno`) REFERENCES `food` (`fno`) ON UPDATE CASCADE ON DELETE CASCADE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;